In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('uber_driver.csv')
df

Unnamed: 0    MMM-YY  Driver_ID   Age  Gender City  Education_Level  \
0               0  01/01/19          1  28.0     0.0  C23                2   
1               1  02/01/19          1  28.0     0.0  C23                2   
2               2  03/01/19          1  28.0     0.0  C23                2   
3               3  11/01/20          2  31.0     0.0   C7                2   
4               4  12/01/20          2  31.0     0.0   C7                2   
...           ...       ...        ...   ...     ...  ...              ...   
19099       19099  08/01/20       2788  30.0     0.0  C27                2   
19100       19100  09/01/20       2788  30.0     0.0  C27                2   
19101       19101  10/01/20       2788  30.0     0.0  C27                2   
19102       19102  11/01/20       2788  30.0     0.0  C27                2   
19103       19103  12/01/20       2788  30.0     0.0  C27                2   

       Income Dateofjoining LastWorkingDate  Joining Designation  Grade  \
0       57387      24/12/18             NaN                    1      1   
1       57387      24/12/18             NaN                    1      1   
2       57387      24/12/18        03/11/19                    1      1   
3       67016      11/06/20             NaN                    2      2   
4       67016      11/06/20             NaN                    2      2   
...       ...           ...             ...                  ...    ...   
19099   70254      06/08/20             NaN                    2      2   
19100   70254      06/08/20             NaN                    2      2   
19101   70254      06/08/20             NaN                    2      2   
19102   70254      06/08/20             NaN                    2      2   
19103   70254      06/08/20             NaN                    2      2   

       Total Business Value  Quarterly Rating  
0                   2381060                 2  
1                   -665480                 2  
2                         0                 2  
3                         0                 1  
4                         0                 1  
...                     ...               ...  
19099                740280                 3  
19100                448370                 3  
19101                     0                 2  
19102                200420                 2  
19103                411480                 2  

[19104 rows x 14 columns]

In [16]:
df.columns

Index(['Unnamed: 0', 'MMM-YY', 'Driver_ID', 'Age', 'Gender', 'City',
       'Education_Level', 'Income', 'Dateofjoining', 'LastWorkingDate',
       'Joining Designation', 'Grade', 'Total Business Value',
       'Quarterly Rating'],
      dtype='object')

In [17]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19104 entries, 0 to 19103
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   MMM-YY                19104 non-null  object 
 1   Driver_ID             19104 non-null  int64  
 2   Age                   19043 non-null  float64
 3   Gender                19052 non-null  float64
 4   City                  19104 non-null  object 
 5   Education_Level       19104 non-null  int64  
 6   Income                19104 non-null  int64  
 7   Dateofjoining         19104 non-null  object 
 8   LastWorkingDate       1616 non-null   object 
 9   Joining Designation   19104 non-null  int64  
 10  Grade                 19104 non-null  int64  
 11  Total Business Value  19104 non-null  int64  
 12  Quarterly Rating      19104 non-null  int64  
dtypes: float64(2), int64(7), object(4)
memory usage: 1.9+ MB


In [19]:
df['MMM-YY'] = pd.to_datetime(df['MMM-YY'])
df['Dateofjoining'] = pd.to_datetime(df['Dateofjoining'])
df['LastWorkingDate'] = pd.to_datetime(df['LastWorkingDate'])

/var/folders/c4/kvf3th_j15lf5cq2pybvfgjm0000gn/T/ipykernel_1394/3944046961.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['MMM-YY'] = pd.to_datetime(df['MMM-YY'])
/var/folders/c4/kvf3th_j15lf5cq2pybvfgjm0000gn/T/ipykernel_1394/3944046961.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dateofjoining'] = pd.to_datetime(df['Dateofjoining'])
/var/folders/c4/kvf3th_j15lf5cq2pybvfgjm0000gn/T/ipykernel_1394/3944046961.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['LastWorkingDate'] = pd.to_datetime(df['LastWorkingDate'])


In [20]:
df.head(5)

MMM-YY  Driver_ID   Age  Gender City  Education_Level  Income  \
0 2019-01-01          1  28.0     0.0  C23                2   57387   
1 2019-02-01          1  28.0     0.0  C23                2   57387   
2 2019-03-01          1  28.0     0.0  C23                2   57387   
3 2020-11-01          2  31.0     0.0   C7                2   67016   
4 2020-12-01          2  31.0     0.0   C7                2   67016   

  Dateofjoining LastWorkingDate  Joining Designation  Grade  \
0    2018-12-24             NaT                    1      1   
1    2018-12-24             NaT                    1      1   
2    2018-12-24      2019-03-11                    1      1   
3    2020-11-06             NaT                    2      2   
4    2020-11-06             NaT                    2      2   

   Total Business Value  Quarterly Rating  
0               2381060                 2  
1               -665480                 2  
2                     0                 2  
3                     0                 1  
4                     0                 1

In [21]:
df.Age.unique()

array([28., 31., 43., 29., 34., 35., 30., 39., 42., 27., 26., nan, 33.,
       40., 41., 32., 22., 44., 36., 21., 49., 37., 38., 46., 47., 48.,
       25., 24., 45., 51., 52., 23., 50., 53., 54., 55., 58.])

In [22]:
# Fill NaN values with the median of the Age column
df['Age'] = df['Age'].fillna(df['Age'].median())

# Convert the Age column to integers
df['Age'] = df['Age'].astype(int)

df.Age.unique()

array([28, 31, 43, 29, 34, 35, 30, 39, 42, 27, 26, 33, 40, 41, 32, 22, 44,
       36, 21, 49, 37, 38, 46, 47, 48, 25, 24, 45, 51, 52, 23, 50, 53, 54,
       55, 58])

In [23]:
df.isna().sum()

MMM-YY                      0
Driver_ID                   0
Age                         0
Gender                     52
City                        0
Education_Level             0
Income                      0
Dateofjoining               0
LastWorkingDate         17488
Joining Designation         0
Grade                       0
Total Business Value        0
Quarterly Rating            0
dtype: int64

In [24]:
df.Gender.unique()

array([ 0.,  1., nan])

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19104 entries, 0 to 19103
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   MMM-YY                19104 non-null  datetime64[ns]
 1   Driver_ID             19104 non-null  int64         
 2   Age                   19104 non-null  int64         
 3   Gender                19052 non-null  float64       
 4   City                  19104 non-null  object        
 5   Education_Level       19104 non-null  int64         
 6   Income                19104 non-null  int64         
 7   Dateofjoining         19104 non-null  datetime64[ns]
 8   LastWorkingDate       1616 non-null   datetime64[ns]
 9   Joining Designation   19104 non-null  int64         
 10  Grade                 19104 non-null  int64         
 11  Total Business Value  19104 non-null  int64         
 12  Quarterly Rating      19104 non-null  int64         
dtypes: datetime64[ns

In [26]:
df.Gender = df.Gender.astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19052 entries, 0 to 19103
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   MMM-YY                19052 non-null  datetime64[ns]
 1   Driver_ID             19052 non-null  int64         
 2   Age                   19052 non-null  int64         
 3   Gender                19052 non-null  int64         
 4   City                  19052 non-null  object        
 5   Education_Level       19052 non-null  int64         
 6   Income                19052 non-null  int64         
 7   Dateofjoining         19052 non-null  datetime64[ns]
 8   LastWorkingDate       1611 non-null   datetime64[ns]
 9   Joining Designation   19052 non-null  int64         
 10  Grade                 19052 non-null  int64         
 11  Total Business Value  19052 non-null  int64         
 12  Quarterly Rating      19052 non-null  int64         
dtypes: datetime64[ns](3),

In [16]:
df.dropna(subset=['Gender'], inplace=True)

In [18]:
df.isna().sum()

MMM-YY                      0
Driver_ID                   0
Age                         0
Gender                      0
City                        0
Education_Level             0
Income                      0
Dateofjoining               0
LastWorkingDate         17441
Joining Designation         0
Grade                       0
Total Business Value        0
Quarterly Rating            0
dtype: int64

In [20]:
df.head(5)

MMM-YY  Driver_ID  Age  Gender City  Education_Level  Income  \
0 2019-01-01          1   28     0.0  C23                2   57387   
1 2019-02-01          1   28     0.0  C23                2   57387   
2 2019-03-01          1   28     0.0  C23                2   57387   
3 2020-11-01          2   31     0.0   C7                2   67016   
4 2020-12-01          2   31     0.0   C7                2   67016   

  Dateofjoining LastWorkingDate  Joining Designation  Grade  \
0    2018-12-24             NaT                    1      1   
1    2018-12-24             NaT                    1      1   
2    2018-12-24      2019-03-11                    1      1   
3    2020-11-06             NaT                    2      2   
4    2020-11-06             NaT                    2      2   

   Total Business Value  Quarterly Rating  
0               2381060                 2  
1               -665480                 2  
2                     0                 2  
3                     0                 1  
4                     0                 1